"addi t1, zero, 0 \n\t" //i
"addi %[add_cnt], %[add_cnt], 1 \n\t"

"loop: \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"bge t1, %[N], end \n\t"
"li t3, 2 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"rem t2, t1, t3 \n\t" //t2=t1%t3
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"li t4, 1 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"beq t2, t4, odd \n\t"
"li t4, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"beq t2, t4, even \n\t"

"odd: \n\t"
"li t2, 2 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"mul t2, t2, t1 \n\t"
"addi %[mul_cnt], %[mul_cnt], 1 \n\t"
"addi t2, t2, 1 \n\t" //(2*i+1)
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"fcvt.d.w f2, t2 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"li t3, -1 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"fcvt.d.w f1, t3 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"fdiv.d f1, f1, f2 \n\t"
"addi %[div_cnt], %[div_cnt], 1 \n\t"
"fadd.d %[pi], %[pi], f1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi t1, t1, 1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"j loop \n\t"

"even: \n\t"
"li t2, 2 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"mul t2, t2, t1 \n\t"
"addi %[mul_cnt], %[mul_cnt], 1 \n\t"
"addi t2, t2, 1 \n\t" //(2*i+1)
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"fcvt.d.w f2, t2 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"li t3, 1 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"fcvt.d.w f1, t3 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"fdiv.d f1, f1, f2 \n\t"
"addi %[div_cnt], %[div_cnt], 1 \n\t"
"fadd.d %[pi], %[pi], f1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi t1, t1, 1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"j loop \n\t"

"end: \n\t"